name: React Native CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: ./Main
        run: npm install

      - name: Install firebase
        working-directory: ./Main
        run: npm install firebase
      
        
        

